<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = true;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Completa il tuo ordine con');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = true;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('Potresti essere interessato anche a');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = true;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = true;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = true;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist) :?>

<?php if ($type == 'related' || $type == 'upsell') :?>
<?php if ($type == 'related') :?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
<?php else :?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= $block->escapeHtmlAttr($limit) ?>" data-shuffle="<?= /* @noEscape */ $shuffle ?>">
<?php endif; ?>
<?php else :?>
<div class="block <?= $block->escapeHtmlAttr($class) ?>">
    <?php endif; ?>
    <div class="container">
        <div class="row">
            <h2 class="block-title title col-12">
                <div class="heading-wrapper" id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2">
                    <span>
                        <?= $block->escapeHtml($title) ?>
                    </span>
                    <span>
                    <?php if ($type == 'related' && $canItemsAddToCart) :?>
                        <div class="block-actions">
                            <button type="button" class="action select" role="button">
                                <span>
                                    <?= $block->escapeHtml(__('Spunta i prodotti per aggiungerli al carrello')) ?>
                                </span>
                            </button>
                        </div>
                    <?php endif; ?>
                    </span>
                </div>
            </h2>
            <div class="block-content content col-12" aria-labelledby="block-<?= $block->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items">
                        <?php foreach ($items as $_item) :?>
                            <?php $available = ''; ?>
                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') :?>
                                <?php if (!$_item->getRequiredOptions()) :?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell') :?>
                                <li class="item product product-item" style="display: none;">
                            <?php else :?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="home-product-info product-item-info <?= /* @noEscape */ $available ?>">
                                <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
                                <?php
                                    if ($_item->getPrice() > $_item->getFinalPrice()):
                                        echo '<div class="salebox">-' . number_format((float)(1 - $_item->getSpecialPrice()/$_item->getPrice()) * 100, 0, '.', ''). '%</div>';
                                    endif;
                                ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                    title="<?= $block->escapeHtml($_item->getName()) ?>"
                                    class="home-product-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="home-product-details">
                                    <?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related') :?>
                                        <?php if (!$_item->getRequiredOptions()) :?>
                                            <div class="field choice related">
                                                <input type="checkbox" class="checkbox related" id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="related_products[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <span class="home-product-name">
                                        <a class="home-product-link"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                            title="<?= $block->escapeHtml($_item->getName()) ?>">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </span>
                                    <div class="home-product-description">
                                        <?php 
                                            $productDesc = $_item->getDescription();
                                            echo strlen($productDesc) > 40 ? substr($productDesc ,0,40)."..." : $productDesc;
                                        ?>
                                    </div>

                                    <?= /* @noEscape */ $block->getProductPrice($_item) ?>

                                    <?php if ($type == 'upsell') :?>
                                        <a class="home-product-purchase"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                            title="<?= $block->escapeHtml($_item->getName()) ?>">
                                            <?= __('DETTAGLI E ACQUISTO') ?>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif;?>
