<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('AGGIUNGI AL CARRELLO'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qtà:')) ?></span></label>
            <div class="control">
                <input type='button' value='-' class='qtyminus' field='qty' />
                <div class="qty-input-wrapper">
                    <input type="number"
                        name="qty"
                        id="qty"
                        min="0"
                        value="<?= $block->getProductDefaultQty() * 1 ?>"
                        title="<?= $block->escapeHtmlAttr(__('Qtà')) ?>"
                        class="input-text qty"
                        data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                    />
                </div>
                <input type="button" value="+" class="qtyplus" field="qty" />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script type="text/javascript">
    //&lt;![CDATA[
    require(['jquery'], function ($) {
        setTimeout(function () {
            // This button will increment the value
            jQuery('.qtyplus').click(function (e) {
                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                fieldName = jQuery(this).attr('field');
                // Get its current value
                var currentVal = parseInt(jQuery('input[name=' + fieldName + ']').val());
                // If is not undefined
                if (!isNaN(currentVal)) {
                    // Increment
                    jQuery('input[name=' + fieldName + ']').val(currentVal + 1);
                } else {
                    // Otherwise put a 1 there
                    jQuery('input[name=' + fieldName + ']').val(1);
                }
            });
            // This button will decrement the value till 1
            jQuery(".qtyminus").click(function (e) {
                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                fieldName = jQuery(this).attr('field');
                // Get its current value
                var currentVal = parseInt(jQuery('input[name=' + fieldName + ']').val());
                // If it isn't undefined or its greater than 1
                if (!isNaN(currentVal) && currentVal > 1) {
                    // Decrement one
                    jQuery('input[name=' + fieldName + ']').val(currentVal - 1);
                } else {
                    // Otherwise put a 1 there
                    jQuery('input[name=' + fieldName + ']').val(1);
                }
            });
        }, 100);
    });
    //]]&gt;
</script>