<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1) :?>
        <?= $block->escapeHtml(
            __(
                'Mostra %1-%2 di %3',
                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1) :?>
        <?= $block->escapeHtml(
            __('%1 Articolo', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Elementi', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php endif; ?>
</p>
