<div class="footer-content-mobile d-flex d-sm-none flex-column">
    <div data-role="collapsible">
        <div data-role="trigger">
            <h6>Informazioni</h6>
        </div>
    </div>
    <div data-role="content">
        <ul>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'chi-siamo'; ?>" title="Chi siamo">Chi siamo</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'contact'; ?>" title="Contattaci">Contattaci</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'help'; ?>" title="Aiuto">Aiuto</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'faq'; ?>" title="FAQ">FAQ</a>
            </li>
        </ul>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h6>Acquisti</h6>
        </div>
    </div>
    <div data-role="content">
        <ul>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'buying-guide'; ?>" title="Guida all’acquisto">Guida all’acquisto</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'terms-conditions'; ?>" title="Termini e condizioni">Termini e condizioni</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'payments'; ?>" title="Pagamenti">Pagamenti</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'shipping-returns'; ?>" title="Spedizioni e restituzioni">Spedizioni e restituzioni</a>
            </li>
        </ul>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h6>Pagamenti</h6>
        </div>
    </div>
    <div data-role="content">
        <p>Pagamenti sicuri con</p>
        <div class="footer-logos-1-images">
            <img src="<?php echo $this->getViewFileUrl('images/footer/paypal.png'); ?>" alt="paypal">
            <img src="<?php echo $this->getViewFileUrl('images/footer/nexi_logo.png'); ?>" alt="nexi_logo">
            <span>Accettiamo anche bonifico bancario e contrassegno</dpan>
        </div>
        <p>Spedizioni in 24/48h con</p>
        <div class="footer-logos-2-images">
            <img src="<?php echo $this->getViewFileUrl('images/footer/gls_logo.png'); ?>" alt="gls_logo">
            <img src="<?php echo $this->getViewFileUrl('images/footer/sda_logo.png'); ?>" alt="sda_logo">
        </div>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h6>Spedizioni</h6>
        </div>
    </div>
    <div data-role="content">
        <ul>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'withdrawal'; ?>" title="Recesso">Recesso</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'privacy-policy-cookie-restriction-mode'; ?>" title="Privacy Policy">Privacy Policy</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'enable-cookies'; ?>" title="Cookies Policy">Cookies Policy</a>
            </li>
            <li>
                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'site-map'; ?>" title="Mappa del sito">Mappa del sito</a>
            </li>
        </ul>
    </div>

    <div class="footer-details-top-left">
        <div class="footer-company-details">
            <p>
                Centro Commerciale Il Ponte <br>
                Via dell’Ala 15-d - 06134 Ponte Felcino (PG) <br>
                PI: 03358320541 <br>
            </p>
            <img src="<?php echo $this->getViewFileUrl('images/footer/footer-01.png'); ?>" alt="Footer Image">
            <p>
                <a href="tel:075691146" title="Tel. 075 691146">Tel. 075 691146</a><br>
                <a href="fax:0756910728" title="Fax 075 6910728">Fax 075 6910728</a><br>
                <a href="mailto:info@farmaciabolli1833.it" title="info@farmaciabolli1833.it">info@farmaciabolli1833.it</a>
            </p>
            <div class="header-top-social-right">
                <a href="#" title="Facebook"><i class="fab fa-facebook-f"></i></a>
                <a href="#" title="Instagram"><i class="fab fa-instagram"></i></a>
            </div>
        </div>
    </div>
</div>

<div class="footer-content-top d-none d-sm-block">
    <div class="container">
        <div class="row">
            <div class="footer-details-top">
                <div class="footer-details-top-left">
                    <div class="footer-company-details">
                        <h6>Farmacia Bolli 1833</h6>
                        <p>
                            Centro Commerciale Il Ponte <br>
                            Via dell’Ala 15-d - 06134 Ponte Felcino (PG) <br>
                            PI: 03358320541 <br>
                        </p>
                        <p>
                            <a href="tel:075691146" title="Tel. 075 691146">Tel. 075 691146</a> - <a href="fax:0756910728" title="Fax 075 6910728">Fax 075 6910728</a><br>
                            <a href="mailto:info@farmaciabolli1833.it" title="info@farmaciabolli1833.it">info@farmaciabolli1833.it</a>
                        </p>
                    </div>
                    <div class="footer-company-img">
                        <img src="<?php echo $this->getViewFileUrl('images/footer/footer-01.png'); ?>" alt="Footer Image">
                    </div>
                </div>
                <div class="footer-details-top-right">
                    <div class="footer-links">
                        <h6>Informazioni</h6>
                        <ul>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'chi-siamo'; ?>" title="Chi siamo">Chi siamo</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'contact'; ?>" title="Contattaci">Contattaci</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'help'; ?>" title="Aiuto">Aiuto</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'faq'; ?>" title="FAQ">FAQ</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-links">
                        <h6>Acquisti</h6>
                        <ul>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'buying-guide'; ?>" title="Guida all’acquisto">Guida all’acquisto</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'terms-conditions'; ?>" title="Termini e condizioni">Termini e condizioni</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'payments'; ?>" title="Pagamenti">Pagamenti</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'shipping-returns'; ?>" title="Spedizioni e restituzioni">Spedizioni e restituzioni</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-links">
                        <h6>Spedizioni</h6>
                        <ul>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'withdrawal'; ?>" title="Recesso">Recesso</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'privacy-policy-cookie-restriction-mode'; ?>" title="Privacy Policy">Privacy Policy</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'enable-cookies'; ?>" title="Cookies Policy">Cookies Policy</a>
                            </li>
                            <li>
                                <a href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . 'site-map'; ?>" title="Mappa del sito">Mappa del sito</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer-content-bottom d-none d-sm-block">
    <div class="container">
        <div class="row">
            <div class="footer-details-bottom">
                <div class="header-top-social-right">
                    <a href="#" title="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" title="Instagram"><i class="fab fa-instagram"></i></a>
                </div>
                <div class="footer-logos">
                    <div class="footer-logos-1">
                        <p>Pagamenti sicuri con</p>
                        <div class="footer-logos-1-images">
                            <img src="<?php echo $this->getViewFileUrl('images/footer/paypal.png'); ?>" alt="paypal">
                            <img src="<?php echo $this->getViewFileUrl('images/footer/nexi_logo.png'); ?>" alt="nexi_logo">
                            <span>Accettiamo anche bonifico bancario e contrassegno</dpan>
                        </div>
                    </div>
                    <div class="footer-logos-2">
                        <p>Spedizioni in 24/48h con</p>
                        <div class="footer-logos-2-images">
                            <img src="<?php echo $this->getViewFileUrl('images/footer/gls_logo.png'); ?>" alt="gls_logo">
                            <img src="<?php echo $this->getViewFileUrl('images/footer/sda_logo.png'); ?>" alt="sda_logo">
                        </div>
                    </div>
                </div>
            </div>
        <div>
    </div>
</div>