<div class="header-details">
    <div class="mobile-text d-flex d-sm-none">
        SERVIZIO<br>
        CLIENTI<br>
        7/7 8-24
    </div>
    <div class="header-detail d-none d-sm-flex">
        <i class="far fa-truck"></i>
        <div class="header-detail-content">
            <p>SPEDIZIONI GRATUITE</p>
            <span>in 24/48h per ordini sopra 49€</span>
        </div>
    </div>
    <div class="header-detail">
        <i class="fal fa-user-headset"></i>
        <div class="header-detail-content d-none d-sm-block">
            <p>+39 075 691 146</p>
            <span>tutti i giorni 8-24</span>
        </div>
    </div>
    <div class="header-detail">
        <i class="fab fa-whatsapp"></i>
        <div class="header-detail-content d-none d-sm-block">
            <p>+39 348 5628328</p>
            <span>tutti i giorni 8-24</span>
        </div>
    </div>
</div>