<div class="header-details">
    <div class="header-detail">
        <i class="far fa-truck"></i>
        <div class="header-detail-content">
            <p>SPEDIZIONI GRATUITE</p>
            <span>in 24/48h per ordini sopra 49€</span>
        </div>
    </div>
    <div class="header-detail">
        <i class="fal fa-user-headset"></i>
        <div class="header-detail-content">
            <p>+39 075 691 146</p>
            <span>tutti i giorni 8-24</span>
        </div>
    </div>
    <div class="header-detail">
        <i class="fab fa-whatsapp"></i>
        <div class="header-detail-content">
            <p>+39 348 5628328</p>
            <span>tutti i giorni 8-24</span>
        </div>
    </div>
</div>