<div class="home-blocks-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-4">
                <div class="home-block">
                    <div class="home-block-img">
                        <img src="<?php echo $this->getViewFileUrl('images/blocks/block-01.png'); ?>" alt="Block-01">
                    </div>
                    <div class="home-block-content">
                        <h5>Rimedi per Allergie</h5>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-4">
                <div class="home-block">
                    <div class="home-block-img">
                        <img src="<?php echo $this->getViewFileUrl('images/blocks/block-02.png'); ?>" alt="Block-02">
                    </div>
                    <div class="home-block-content">
                        <h5>Alimenti Dietetici</h5>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-4">
                <div class="home-block">
                    <div class="home-block-img">
                        <img src="<?php echo $this->getViewFileUrl('images/blocks/block-03.png'); ?>" alt="Block-03">
                    </div>
                    <div class="home-block-content">
                        <h5>Brand in evidenza</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>