<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $_productCollection */
$_productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');

/** Apply filters here */
$category_id = 46;
$_productCollection->addCategoriesFilter(['in' => [$category_id]]);
$_productCollection->addAttributeToSelect('*');
$_productCollection->setPageSize(2);
$_productCollection->load();

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$viewMode = 'list';
$image = 'category_page_list';
$showDescription = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$pos = $block->getPositioned();
?>

<div class="homepage-daily-deals">
    <div class="container">
        <div class="row">
            <div class="home-special-offer">
                <?php
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('homepage-special-offer')
                    ->toHtml();
                ?>
            </div>
            <div class="hand-picked-daily-inside">
                <h2 class="heading-l">
                    <span>daily deals</span>
                </h2>
                <div class="products">
                    <?php $iterator = 1; ?>
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach($_productCollection as $_product): ?>
                        <?= ($iterator++ == 1) ? '<div class="product">' : '</div><div class="product">' ?>
                        <div class="product-actions">
                            <a href="#"
                               data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>'
                               class="action towishlist"
                               data-action="add-to-wishlist">
                                <i class="fas fa-heart fa-lg" aria-hidden="true"></i>
                            </a>
                            <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                <a href="<?php echo $_compareUrl ?>" class="action compare">
                                    <i class="fas fa-chart-bar fa-lg" aria-hidden="true"></i>
                                </a>
                            <?php endif; ?>
                        </div>
                        <div class="product-info" data-container="product-grid">
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>

                            <a href="<?= $_product->getProductUrl() ?>" class="product-photo" tabindex="-1" style="background:url('<?= $productImage->getImageUrl()?>') center;background-size:cover;">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <div class="product-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <a class="product-link"
                                   href="<?= $_product->getProductUrl() ?>">
                                    <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>

                                <?= $block->getProductPrice($_product) ?>
                            </div>

                        </div>
                        <?= ($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>