<div class="home-banner-wrapper">
    <div class="home-banner-slide slide-01">
        <div class="slide-overlay">
            <img src="<?php echo $this->getViewFileUrl('images/banner/slide-01.png'); ?>" alt="Slide-01">
        </div>
        <div class="slide-content">
            <h2>
                Benvenuti sul nostro nuovissimo e-commerce
            </h2>
            <h3>
                Ci siamo rifatti il look! Festeggia con noi con una super promo!
            </h3>
            <h2>
                10% di extra sconto
            </h2>
            <h3>
                Usa il codice <span>NEWBOLLI</span>
            </h3>
            <a href="#" title="NEWBOLLI">APPROFITTANE</a>
        </div>
    </div>
    <div class="home-banner-slide slide-02">
        <div class="slide-overlay">
            <img src="<?php echo $this->getViewFileUrl('images/banner/slide-02.png'); ?>" alt="Slide-02">
        </div>
        <div class="slide-content">
            <h2>
                Combattiamo il CoronaVirus
            </h2>
            <h3>
                Tutti i prodotti per difendersi al meglio e proteggere chi ci sta vicino
            </h3>
            <a href="#" title="SCOPRI I PRODOTTI">SCOPRI I PRODOTTI</a>
        </div>
    </div>
    <div class="home-banner-slide slide-03">
        <div class="slide-overlay">
            <img src="<?php echo $this->getViewFileUrl('images/banner/slide-03.png'); ?>" alt="Slide-03">
        </div>
        <div class="slide-content">
            <h2>
                Promo senza titolo lorem ipsum
            </h2>
            <h3>
                Lorem ipsum dolor sic amet lore ipsum dolor sic amet Lorem Ipsum dolor
            </h3>
            <a href="#" title="APPROFITTANE">NEWBOLLI</a>
        </div>
    </div>
</div>