<div class="col-12 col-sm-6 col-lg-8">
    <div class="home-blog-wrapper">
        <div class="home-blog-content">
            <h4>Blog</h4>
            <h5>Estetica oncologica: <br> la nuova frontiera del benessere</h5>
            <p>L’estetica oncologica nasce dall’esigenza di sostenere e aiutare le persone affette da tumore a prendersi cura della propria bellezza e immagine nonostante la malattia.</p>
            <a href="#" title="leggi sul nostro sito">leggi sul nostro sito</a>
        </div>
        <div class="home-blog-img">
            <img src="<?php echo $this->getViewFileUrl('images/blog-img.png'); ?>" alt="Blog Image">
        </div>
    </div>
</div>