<div class="home-brands">
    <div class="container">
        <div class="row">
            <h2 class="col-12">
                <div class="heading-wrapper">
                    <span><a href="#" title="Brand">Brand</a></span>    
                    <span>
                        <a href="#" title="Vedi tutti">
                            <span>Vedi tutti</span>
                            <i class="fal fa-long-arrow-right"></i>
                        </a>
                    </span>
                </div>
            </h2>
            <div class="col-12 brands">
                <div class="brand col-4 col-lg-2">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-01.png'); ?>" alt="Brand 01">
                </div>
                <div class="brand col-4 col-lg-2">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-02.png'); ?>" alt="Brand 02">
                </div>
                <div class="brand col-4 col-lg-2">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-03.png'); ?>" alt="Brand 03">
                </div>
                <div class="brand col-4 col-lg-2 d-none d-sm-flex">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-04.png'); ?>" alt="Brand 04">
                </div>
                <div class="brand col-4 col-lg-2 d-none d-sm-flex">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-05.png'); ?>" alt="Brand 05">
                </div>
                <div class="brand col-4 col-lg-2 d-none d-sm-flex">
                    <img src="<?php echo $this->getViewFileUrl('images/brands/brand-06.png'); ?>" alt="Brand 06">
                </div>
            </div>
            <div class="col-12 forum">
                <div class="forum-1">
                    <h4>Scopri la nostra farmacia a Perugia</h4>
                    <img src="<?php echo $this->getViewFileUrl('images/forum-01.png'); ?>" alt="Forum">
                </div>
                <div class="forum-2">
                    <h4>Partecipa alla community!</h4>
                    <h6>Scopri tutte le novità e le offerte della nostra farmacia sui nostri social!</h6>
                    <div class="header-top-social-right">
                        <a href="#" title="Facebook"><i class="fab fa-facebook-f"></i></a>
                        <a href="#" title="Instagram"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>