<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $_productCollection */
$_productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');

/** Apply filters here */
$category_id = 4;
$_productCollection->addCategoriesFilter(['in' => [$category_id]]);
$_productCollection->addAttributeToSelect('*');
$_productCollection->setPageSize(10);
$_productCollection->load();

$category_manager = $objectManager->create('Magento\Catalog\Model\Category')->load($category_id);

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$viewMode = 'list';
$image = 'category_page_list';
$showDescription = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();

?>
<div class="home-products-wrapper">
    <div class="container">
        <div class="row">
            <h2 class="col-12">
                <div class="heading-wrapper">
                    <span>
                        <a
                            href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . $category_manager->getData()['url_path'];
                            ?>"
                            title="<?php echo $category_manager->getData()['name']; ?>"
                        >
                            <?php echo $category_manager->getData()['name']; ?>
                        </a>
                    </span>
                    <span>
                        <a
                            href="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]) . $category_manager->getData()['url_path'];
                            ?>"
                            title="<?php echo $category_manager->getData()['name']; ?>"
                        >
                            <span>Vedi tutti</span>
                            <i class="fal fa-long-arrow-right"></i>
                        </a>
                    </span>
                </div>
            </h2>
            <ol class="home-products-list">
                <?php $iterator = 1; ?>
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach($_productCollection as $_product ): ?>
                    <?= ($iterator++ == 1) ? '<li class="home-product">' : '</li><li class="home-product">' ?>
                <div class="home-product-info">
                <?php
                    if ($_product->getPrice()>$_product->getFinalPrice()):
                        echo '<div class="salebox">-' . number_format((float)(1 - $_product->getSpecialPrice()/$_product->getPrice()) * 100, 0, '.', ''). '%</div>';
                    endif;
                ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $_product->getProductUrl() ?>"
                    class="home-product-photo" tabindex="-1"
                    title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>"
                    style="background:url('<?= $productImage->getImageUrl()?>') center;background-size:cover;">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="home-product-details">
                        <span class="home-product-name">
                            <a class="home-product-link"
                                href="<?= $_product->getProductUrl() ?>"
                                title="<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>">
                                <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </span>
                        <div class="home-product-description">
                            <?php echo strlen($_product->getDescription()) > 40 ? substr($_product->getDescription() ,0,40)."..." : $_product->getDescription(); ?>
                        </div>
                        <?= $block->getProductPrice($_product) ?>
                        <a class="button-details" href="<?= $_product->getProductUrl() ?>" title="DETTAGLI E ACQUISTO"><?= __('DETTAGLI E ACQUISTO')?></a>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>