<div class="home-features-wrapper">
    <div class="container">
        <div class="row">
            <h4 class="col-12 d-none d-sm-block">Oltre 20.000 integratori, cosmetici, farmaci e parafarmaci in vendita a prezzi scontati</h4>
            <div class="home-feature col-12 col-sm-6 col-lg-3">
                <div class="home-feature-icon">
                    <i class="fal fa-user-headset"></i>
                </div>
                <div class="home-feature-content">
                    <h5>Qui per te 24/7</h5>
                    <p>Siamo a tua completa disposizione dalle 8 alle 24, 365 giorni l’anno!</p>
                </div>
            </div>
            <div class="home-feature col-sm-6 col-lg-3 d-none d-sm-flex">
                <div class="home-feature-icon">
                    <i class="far fa-truck"></i>
                </div>
                <div class="home-feature-content">
                    <h5>Subito a casa tua</h5>
                    <p>Spedizioni tracciabili con corriere espresso in 24/48h, gratuite da 49€</p>
                </div>
            </div>
            <div class="home-feature col-sm-6 col-lg-3 d-none d-sm-flex">
                <div class="home-feature-icon">
                    <i class="far fa-window"></i>
                </div>
                <div class="home-feature-content">
                    <h5>Tutto quello che serve</h5>
                    <p>Un catalogo di oltre 20.000 prodotti per ogni esigenza!</p>
                </div>
            </div>
            <div class="home-feature col-sm-6 col-lg-3 d-none d-sm-flex">
                <div class="home-feature-icon">
                    <i class="fas fa-store"></i>
                </div>
                <div class="home-feature-content">
                    <h5>Quasi 200 anni di storia</h5>
                    <p>Siamo una delle farmacie più grandi d’Italia, nata nel 1833</p>
                </div>
            </div>
        </div>
    </div>
</div>